apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/AkramDhiabi/notaben_assignement.git
    targetRevision: main
    path: helm-chart/simple-app
    helm:
      releaseName: simple-app

  destination:
    server: https://kubernetes.default.svc
    namespace: nb-challenge

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
